import os
import requests
import random 

# Get environment variables
MODEL_ID = os.getenv('MODEL_ID')
MODEL_KEY = os.environ.get('MODEL_KEY')
MODEL_CLASS = os.environ.get('MODEL_CLASS')
MODEL_STEPS = int(os.environ.get('MODEL_STEPS'))
BATCH_SAMPLES = int(os.environ.get('BATCH_SAMPLES'))

# prm = "_KEYS_ some string ^ _KEYS_ another string"
prm = os.environ.get('PR')
prm = prm.replace("_KEYS_", f"{MODEL_KEY} {MODEL_CLASS}")
splittedPrompts = prm.split("^")

professions = [
    'Medieval FIghter',
    'Medieval Magician',
    'Medieval Priest',
    'Medieval Hunter',
    'Medieval Wizard',
    'Medieval Merchant',
    'Medieval Thief',
    'Medieval Mage Apprentice',
    'Medieval Cleric',
    'Medieval Archer',
    'Medieval Blacksmith',
    'Medieval Tailor',
    'Medieval Doctor',
    'Medieval Soldier',
    'Medieval Alchemist',
    'Medieval Enchantress',
    'Medieval Builder',
    'Medieval Cook',
    'Medieval Baker',
    'Medieval Fisherman',
    'Medieval Herbalist',
    'Medieval Carver',
    'Medieval Farmer',
    'Medieval Miner',
    'Medieval Librarian',
    'Medieval Priestess',
    'Medieval Smith',
    'Medieval Town Clerk',
    'Medieval Bard',
    'Medieval Scout',
    'Medieval Groom',
    'Medieval Butler',
    'Medieval Engineer',
    'Medieval Minstrel',
    'Medieval Steward',
    'Medieval Mayor',
    'Medieval Shipbuilder',
    'Medieval Geographer',
    'Medieval Shipwright',
    'Medieval Spy',
    'Medieval Enchanter',
    'Medieval Governor',
    'Medieval Diplomat',
    'Medieval Explorer',
    'Medieval General',
    'Medieval Knight Commander',
    'Medieval Ambassador',
    'Medieval King',
    'Medieval Queen',
    'Medieval Courtesan',
    'Medieval Royal Guard',
    'Medieval Swordsman',
    'Medieval Knight',
    'Medieval Rider',
    'Medieval Messenger',
    'Medieval Summoner',
    'Medieval Student',
    'Medieval Scholar',
    'Medieval Rival',
    'Medieval Prince',
    'Medieval Princess',
    'Medieval Goddess',
    'Medieval Spirit',
    'Medieval God',
    'Medieval Demon',
    'Medieval Holy Warrior',
    'Medieval Ruler',
    'God Emperor',
    'God of War',
    'God of Death',
    'God of Love',
    'God of Truth',
    'God of Knowledge',
    'God of Magic',
    'God of Wisdom',
    'God of Creation',
    'God of Chaos',
    'God of Destruction',
    'God of Life',
    'God of Good Fortune',
    'God of Evil',
    'Cyber Smasher',
    'Cyber Hacker',
    'Cyber Spy',
    'Cyber Mechanic',
    'Cyber Courier',
    'Cyber Gunfighter',
    'Cyber Biker',
    'Cyber Cyber Magician',
    'Cyber Doctor',
    'Cyber Soldier',
    'Cyber Black Ops',
    'Cyber Artist',
    'Cyber Seer',
    'Cyber Operator',
    'Cyber Scholar',
    'Cyber Mercenary',
    'Cyber Mechanoid',
    'Cyber Scientist',
    'Cyber Politician',
    'Cyber Bounty Hunter',
    'Cyber Brute',
    'Cyber Rogue',
    'Cyber Diva',
    'Cyber Aristocrat',
    'Cyber Raconteur',
    'Cyber Warrior King',
    'Cyber Lord',
    'Cyber Sorcerer General',
    'Cyber Emperor',
    'War Soldier',
    'War Infantry',
    'War Commando',
    'War Ranger',
    'War Light MechWarrior',
    'War Heavy MechWarrior',
    'War Engineer',
    'War Tech',
    'War Medic',
    'War Special Ops',
    'War Executive',
    'War Political',
    'War Admiral',
    'War General',
    'War Vice President',
    'War King',
    'War God',
    'Cyber Mech Warrior',
    'Cyber Bot operator',
    'Cyber Augmentation Doctor',
    'Cyber Bounty hunter',
    'Cyber Private investigator',
    'Cyber Corporate Spy',
    'Cyber Assassin',
    'Cyber Rigger',
    'Cyber Information broker',
    'Cyber Escort',
    'Cyber Drone pilot',
    'Cyber Enforcer',
    'Cyber Pirate',
    'Cyber Ship Captain',
    'Cyber Terrorist',
    'Cyber Vigilante',
    'Cyber Black Marketeer',
    'Cyber Roboticist',
    'Cyber Infiltrator',
    'Cyber Teleportation Specialist',
    'Cyber Technician',
    'Cyber Medical technician',
    'Cyber Bodyguard',
    'Cyber Criminal psychologist',
    'Cyber Robot bodybuilder',
    'Post-Apocalypse Radiation specialist',
    'Post-Apocalypse Nuker',
    'Post-Apocalypse Laser Guard',
    'Post-Apocalypse Infected',
    'Post-Apocalypse Snare',
    'Post-Apocalypse Shock Trooper',
    'Post-Apocalypse Biometrics Specialist',
    'Post-Apocalypse Hard Core',
    'Post-Apocalypse Killer',
    'Post-Apocalypse Sniper',
    'Post-Apocalypse Paranoid',
    'Post-Apocalypse Tech Master',
    'Post-Apocalypse Mechanic',
    'Post-Apocalypse Hacker',
    'Post-Apocalypse Scavenger',
    'Post-Apocalypse Enforcer',
    'Post-Apocalypse Medic',
    'Post-Apocalypse Security Chief',
    'Post-Apocalypse Hacking Technician',
    'Post-Apocalypse Brawler',
    'Post-Apocalypse Brawler Extra',
    'Post-Apocalypse Special Forces',
    'Post-Apocalypse Commando',
    'Post-Apocalypse Scout',
    'Post-Apocalypse Commando Extra',
    'Post-Apocalypse Ranger',
    'Post-Apocalypse Engineer',
    'Post-Apocalypse Demolition Expert',
    'Post-Apocalypse Ranger Extra',
    'Post-Apocalypse Military Commando',
    'Post-Apocalypse Special Forces Commando',
    'Post-Apocalypse Elite Soldier',
    'Post-Apocalypse Hunter',
    'Post-Apocalypse Spy',
    'Post-Apocalypse Night Watchman',
    'Post-Apocalypse Double Agent',
    'Post-Apocalypse Smuggler',
    'Post-Apocalypse Spies',
    'Post-Apocalypse Super Smuggler',
    'Post-Apocalypse Smuggler Extra',
    'Post-Apocalypse Super Smugglers',
    'Post-Apocalypse Mercenary',
    'Post-Apocalypse Mercenaries',
    'Nature Shaman',
    'Nature Hunter',
    'Nature Warrior',
    'Nature Cleric',
    'Nature Magician',
    'Nature Wizard',
    'Nature Witchdoctor',
    'Nature Druid',
    'Nature Priestess',
    'Nature Sorcerer',
    'Nature Priest',
    'Corporate Secretary',
    'Corporate Investor',
    'Corporate Manager',
    'Corporate Hacker',
    'Corporate Banker',
    'Corporate Worker',
    'Corporate Military',
    'Corporate Spy',
    'Corporate Lawyer',
    'Corporate Politician',
    'Corporate Artist',
    'Corporate Architect',
    'Corporate Philosopher',
    'Corporate Writer',
    'Corporate Engineer',
    'Corporate Soldier',
    'Corporate Merchant',
    'Corporate Trader',
    'Urban Student',
    'Urban Teacher',
    'Urban Engineer',
    'Urban Musician',
    'Urban KPOP Artist',
    'Urban Singer',
    'Urban DJ ',
    'Urban Jogger ',
    'Urban Martial Arts Master ',
    'Urban Journalist ',
    'Urban Military Leader ',
    'Urban Ninja ',
    'Urban Monk',
    'Urban Criminal',
    'Urban Exotic Dancer ',
    'Urban Thief',
    'Urban Wrestler',
    'Urban Mixed Martial Artist ',
    'Urban Bodyguard',
    'Urban Lawyer',
    'Urban Doctor',
    'Urban Priest',
    'Urban Politician',
    'Urban Spy',
    'Urban Social Media Expert',
    'Urban Forensics Expert ',
    'Urban Detective',
    'Urban Paranormal Investigator ',
    'Urban Alien Researcher ',
    'Urban Devil Worshiper',
    'Urban Vampire Hunter ',
    'Urban Demon Slayer',
    'Urban Pyromaniac',
    'Urban Witch',
    'Urban Demon Hunter',
    'Urban Space Travel Agent',
    'Urban Evil Overlord '
]


for prompt in splittedPrompts:
    # randomize for now
    prompt = random.choice(professions)
    r = requests.get('https://lexica.art/api/v1/search?q=' + prompt.replace(' ', '+')) 
    r.json()
    images = r.json()['images']

    # print(images[0]['id'])
    for idx in range(BATCH_SAMPLES):
        get_ipython().system(
            f"""
            python scripts/stable_txt2img.py \
                --ddim_eta 0.0 \
                --n_samples 1 \
                --n_iter $BATCH_ITER \
                --scale 7.0 \
                --ddim_steps 50 \
                --ckpt "./trained_models/$MODEL_ID.ckpt" \
                --prompt "{MODEL_KEY + ' ' + MODEL_CLASS + ' as ' + random.choice(images)['prompt']}"
            """
        )
        print('prompting for ' + MODEL_KEY + ' ' + MODEL_CLASS + ' as ' + random.choice(images)['prompt'])